controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login:
    path: /api/login
    methods: POST
api_signup:
    path: /api/signup
    controller: App\Controller\SignupController::index
    methods: POST
api_analyse:
    path: /api/analyze
    controller: App\Controller\AnalyseController::analyse
    methods: [GET, POST]
