services:

  database:
    image: mariadb:10.11.2
    container_name: database
    ports:
      - ${DB_PORT}
    volumes:
      - database_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    restart: always

  php-fpm:
    container_name: backend
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  frontend:
    build:
      context: ./../
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - php-fpm
    container_name: frontend
    ports:
      - ${NGINX_FRONT_PORT}:${NGINX_FRONT_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true


  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

volumes:
    database_data:
        driver: local
    redis_data:
        driver: local