name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      database:
        image: mariadb:latest
        env:
          MARiaDB_ROOT_PASSWORD: root Mot de passe pour root
          MARIADB_DATABASE: eco_concept_test
        options: >
          --health-cmd="mysqladmin ping -u root -p$MARIADBQL_ROOT_PASSWORD" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
        ports:
          - 3307:3306
        volumes:
          - db_data:/var/lib/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql, redis
          ini-values: date.timezone=UTC
          coverage: xdebug

      - name: Install Symfony dependencies
        run: |
          cd backend
          composer install

      - name: Run Symfony tests
        env:
          DATABASE_URL: "mysql://root:root_password@127.0.0.1:3306/eco_concept_test"
        run: |
          cd backend
          php bin/phpunit --testdox

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: echo "Add deployment steps here"
